# Generated by Django 4.1.2 on 2023-04-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_id", models.TextField()),
                ("car_data", models.JSONField()),
                ("created", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
