# Generated by Django 4.1.2 on 2023-04-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_cardata_body_typ_cardata_make_cardata_mileage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardata",
            name="fuel",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
